apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluxcloud.fullname" . }}
  labels:
    {{- include "fluxcloud.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.fluxcloud.listenPort }}
      targetPort: {{ .Values.fluxcloud.listenPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fluxcloud.selectorLabels" . | nindent 4 }}
